lightvector/KataGo

cpp/CMakeLists.txt
cpp/core/rand.cpp
cpp/external/zstr/src/strict_fstream.hpp
cpp/game/boardhistory.cpp

Uses clang compiler installed with XCode, cmake and libraries installed
with homebrew.

Fix compilation on Mac OS.

---

python/shuffle.py

instead of blob import, just import the 3 things we actually use

Should fix issue with not running

---

cpp/program/play.cpp

Just a small fix that clang warned about.

Fix compiler warning

---

README.md

Specifically documents where the networks and config files are installed.
What do you think? Should there be more documentation?

Document installation via home-brew

---

python/model.py

As you proposed on discord, just suggesting we merge this in as others are also using this.

Fix for model.py territory scoring

---

cpp/command/gtp.cpp
cpp/search/searchresults.cpp
docs/GTP_Extensions.md

Reverts lightvector/KataGo#430

Revert "Add psv to analyze commands"

---

python/summarize_sgfs.py

Here is the python file. Please take a look, and let me know your thoughts. Then I can modify format.

Add a python file to summarize game results in sgfs file format

---

python/elo.py
python/summarize_sgfs.py

Add a python script to implement some Elo computation stuff. Work in progress.

Add elo script

---

python/elo.py
python/summarize_sgfs.py

Some polishing up work on the sgf Elo script.

Polishing up summarize sgfs

---

python/summarize_sgfs.py

Very minor typo changes in the documentation part.

revise some typos in the comments

---

docs/GTP_Extensions.md

Minor documentation update, feel free to bikeshed the wording.

Added documentation of new gtp raw-nn outputs

---

.gitignore

Add files to ignore when using VS in windows

Add files to ignore when using VS in windows

---

cpp/command/tune.cpp
cpp/neuralnet/openclbackend.cpp
cpp/neuralnet/openclhelpers.cpp
cpp/neuralnet/openclhelpers.h
cpp/neuralnet/opencltuner.cpp
cpp/neuralnet/opencltuner.h
cpp/tests/testnnevalcanary.cpp

Branch for fixing opencl tuning issues reported in v1.12.*

Openclfixes

---

cpp/neuralnet/trtbackend.cpp

Fix trt perf regression for some GPUs

---

cpp/search/search.cpp
cpp/search/searchnode.cpp
cpp/search/searchnode.h

To clarify the meaning of the variables.

Typedef the progress state of a SearchNode

---

cpp/search/search.cpp

Remove unused `numChildren`.
Replace `foundChildIdx` with child pointer.
Remove unnecessary `foundChild`.
---
This was not tested.

Cleanup Search::makeMove()

---

cpp/game/board.cpp
cpp/game/board.h
cpp/neuralnet/nneval.cpp
cpp/neuralnet/nninputs.cpp
cpp/neuralnet/nninputs.h
cpp/search/reportedsearchvalues.cpp
cpp/search/searchhelpers.cpp
cpp/search/searchresults.cpp
cpp/tests/testscore.cpp

Avoid duplicate work,
Simplify calculations,
Reduce dependencies.

Replace Board reference with just board size

---

Compiling.md
cpp/CMakeLists.txt
cpp/neuralnet/trtbackend.cpp

This PR is an update to the TensorRT backend which includes the following changes:
- Reduced initialization time for Ampere and later GPU architectures.
- Allow TensorRT patch version upgrades without recompiling.
- Support for CUDA 12 from TensorRT 8.6 release.

TensorRT backend improvements

---

cpp/command/writetrainingdata.cpp
cpp/core/global.h
cpp/neuralnet/cudabackend.cpp
cpp/neuralnet/openclbackend.cpp

Fixed compile warnings on VC++ 2022 and GCC 11.4.0.

Fix warning

---

python/selfplay/train.sh

"TRANINGNAME" -> "TRAININGNAME"

Fix typo in train.sh
