lightvector/KataGo

README.md, cpp/CMakeLists.txt
Right now, if one calls CMake with either `-DUSE_OPENCL_BACKEND=1` or `-DUSE_CUDA_BACKEND=1` and later wants to switch to the other backend, one needs to explicitly clear the old option in the next CMake call or manually remove or manipulate `CMakeCache.txt` first.
=> Make CMake neural net backend options mutually exclusive

cpp/neuralnet/openclhelpers.cpp
Was trying to set up a one-playout katago on a CPU-only VPS only to find out that CPUs aren't allowed for some reason. I can't see any reason why we shouldn't allow KataGo to run on the CPU. I get 1 playout per second, which is pretty slow, but considering that KataGo 1 playout is stronger than Leela 11 at 10k playouts, it's far from unusable. Thoughts?
=> Allow KataGo to use CPU

cpp/benchmark.cpp
Add a ternary search feature (through `-s` flag) that allows us to optimize between large thread ranges with significantly reduced computation. This will allow for much easier and quicker benchmarking on extremely powerful hardware. Control the maximum number of threads to search up to with `-m`. The higher the maximum, the more beneficial ternary search will be. 
(It's important to note that the ternary search will never be perfect, since the function of threads to strength isn't completely convex and has some noise built in. However, the estimate is fairly close to the maximum strength option. For small thread counts and moderate strength hardware, just testing manually with `-t` is probably good enough.)
The ternary search feature is also beneficial in that it provides a way to search …
=> Better benchmarking with ternary search + adjusting time/move

python/shuffle.py
I got bitten by this, I uncommented them to see if the function gets called; but since they don't have `flush=True` they don't print anything
I think they should just be removed as part of cleanup
=> Removing old commented out print statements

cpp/command/analysis.cpp, cpp/core/global.h, cpp/core/threadsafequeue.h
Implements #179 
tested and found working with https://github.com/sanderland/katrain/pull/12
after loading an sgf and rewinding, you can analyze moves near the beginning. of course there is some small delay since you need to wait for an analysis thread to free up, but it's much better than before.
=> implement priority for analysis engine

cpp/command/gtp.cpp, cpp/configs/gtp_example.cfg, cpp/program/gtpconfig.cpp
If the estimated lead is below resignNotCloseScore don't resign.
=> Don't resign close games config parameter added

cpp/command/analysis.cpp, cpp/core/config_parser.cpp, cpp/core/config_parser.h, cpp/core/threadsafequeue.h
started with a single setting and ended up with this.
- allows for overriding most settings in the config file with an overrideSettings field
- Unrelated, also makes the process exit nicer so you can
./katago analysis ... < input.in
and it will finish all queries before exiting. I wasn't sure why it's currently killing queries so harsh when finding EOF, so happy to not have this in if there's a good reason.
Docs are todo, but thought I'd first pass this by you in case you're very opposed :)
=> overrideSettings in analysis

cpp/command/gtp.cpp, cpp/game/board.cpp, cpp/game/board.h, cpp/program/setup.cpp, cpp/search/search.cpp, cpp/search/search.h, cpp/search/searchparams.cpp, cpp/search/searchparams.h
Just for fun - a feature to maybe kinda do better in mirror Go when the opponent holds an 90+% advantage (e.g. reverse komi mirror go), as opposed to even-game mirror go, which is much easier to handle.
=> Anti-mirror logic

cpp/CMakeLists.txt, cpp/neuralnet/cudabackend.cpp
This patch builds on #295 by @Harald-Han by adding some macro tests to use the appropriate code depending on whether we are compiling against cuDNN7 or cuDNN8. I've also updated the CMakeLists.txt file to use the appropriate gencode settings depending on whether we are using CUDA 10.x or CUDA 11.x.
This should be fully compatible with all existing builds out there, and of course now adds compatibility with systems running with the newer CUDA versions and should add support for Ampere devices with the new gencode settings.
I've tested the build on both CUDA 10/cuDNN 7 and CUDA 11/cuDNN 8 systems.
I have not personally validated the correctness of the cuDNN8 port, but it seemed pretty straight forward and looked good from my naive perspective, however I don't have enough experience with …
=> Add support for CUDA 11 and cuDNN8 (without breaking CUDA 10 / cuDNN7)

cpp/command/analysis.cpp, cpp/search/search.h, cpp/search/searchresults.cpp
This includes the ownership map in all 'moveInfos' objects for the analysis engine.
Probably needs some cleaning up and could be optimized, but opening this PR to see if you're interested in including this.
I'm using it to experiment with 'simple moves' AIs on the front-end side.
=> Return ownership for all candidate moves

cpp/command/analysis.cpp, cpp/command/gtp.cpp, cpp/command/misc.cpp, cpp/search/asyncbot.cpp, cpp/search/asyncbot.h, cpp/search/search.cpp, cpp/search/search.h, cpp/search/searchresults.cpp, docs/Analysis_Engine.md
Adds `reportDuringSearchEvery` option to analysis engine to allow for ongoing reporting during an analysis.
Adds the ability to prematurely terminate earlier-submitted queries to the analysis engine.
See draft of updated docs here:
https://github.com/lightvector/KataGo/blob/ongoing-analysis/docs/Analysis_Engine.md
=> Implement periodic partial reports and termination in analysis engine

cpp/core/rand.cpp
A very trivial fix that a compiler warning pointed out to me.
=> fix mismatched new delete

README.md, cpp/CMakeLists.txt, cpp/command/benchmark.cpp, cpp/command/commandline.cpp, cpp/command/matchauto.cpp, cpp/core/global.cpp, cpp/dataio/homedata.cpp, cpp/dataio/loadmodel.cpp, cpp/external/filesystem-1.3.6/LICENSE, cpp/external/filesystem-1.3.6/README.md, cpp/external/filesystem-1.3.6/include/ghc/filesystem.hpp
Currently the only thing KataGo is utilizing from boost is the `filesystem` library. I thought having a dependency on such a heavyweight library is not the greatest thing in the world. Therefore:
- [Filesystem library](https://github.com/gulrak/filesystem) was used instead, which is a header-only implementation of C++17 `std::filesystem` for C++11, C++14 and C++17.
- `filesystem.hpp` was added in `/external/filesystem-1.3.6/include/ghc/`.
- `<boost/filesystem.hpp>` was replaced to `"../external/filesystem-1.3.6/include/ghc/filesystem.hpp"`.
- `boost::filesystem` was replaced to `ghc::filesystem`.
I tested it on a linux system and it worked fine, but haven't really tested on a Windows system. Also this change raises some warning when making due to switches in `filesystem.hpp` missing …
=> Remove Boost library dependency

cpp/CMakeLists.txt
The `CMAKE_SYSTEM_PROCESSOR` cmake variable takes on a few different values for different arm systems, so this patch just adds those values in.
For anyone curious, this was the only modification needed to get KataGo to build on NVidia's Jetson Nano 2G board, which detects as `aarch64`. The device benchmarks at 11.32 visits/s :)
=> Fix build on aarch64 and aarch32 systems

cpp/command/evalsgf.cpp, cpp/game/board.cpp, cpp/game/board.h, cpp/game/boardhistory.cpp, cpp/game/boardhistory.h, cpp/search/search.cpp, cpp/search/search.h, cpp/tests/results/runOutputTests.txt, cpp/tests/testrules.cpp, docs/rulesv1.html
Fixes a bug in the implementation of Japanese rules that would cause misevaluation of basic double ko death.
See discussion here of the issue:
https://lifein19x19.com/viewtopic.php?f=45&t=17963
=> Jp rules patch

cpp/tests/testboardarea.cpp
`NNInputs::fillScoring()` uses `Board::MAX_ARR_SIZE`, but tests use `NNPos::MAX_BOARD_AREA`
=> Fix buffer overrun in Tests::runBoardAreaTests()

cpp/command/contribute.cpp
In some corner cases, ex. hit ctrl-c when all task loops are downloading models, performance would not be reported.
=> Ensure performance reported

cpp/game/board.cpp, cpp/game/board.h
Some modifications in Benson's algorithm region building algorithm to improve efficiency.
Based on the testing (https://github.com/fuhaoda/GoProject/blob/improvedbenson/DrBombeExplore/benchmarksolutions.cpp)
It can improve efficiency and can reduce time from 10.95 seconds to 8.26 seconds in release mode.
Overall, the codes are very well written, and I have tried many small modifications without too much improvement but reduce the code readability, then I discarded those changes. The current changes are the most significant improvements without change the input/output and structures.  
Two changes.
1) add isVlenNonZero into regionBuild function to improve efficiency
2) use memset to initialize vector. The internal std::fill (the implementation is a iteration) or iteration based …
=> Slightly changed calculateAreaForPla to improve efficiency

python/train.py
Mentioned in [issue #526](https://github.com/lightvector/KataGo/issues/526).
=> add swa_model assignmeng_mapping for finetuning weight loading

cpp/configs/match_example.cfg, cpp/program/playsettings.cpp
As we discussed last week, here are some settings loaded into `PlaySettings PlaySettings::loadForMatch(ConfigParser& cfg)`. So people can add additional parameter to increase the small board match opening.
=> add match options for small board

docs/KataGoMethods.md
Thank you for the clear document and now I better understand what I was testing for : )
I kept the order of exploitation vs exploration as the same order in the PUCT formula.
=> Very small typo in the document.

python/summarize_sgfs.py
passed test on the damaged sgfs files
=> handle errors/execptions when summarize sgfs files

cpp/command/benchmark.cpp
Hi.
I am not sure the original code is intentional or not, benchmark command ignores defaultBoardSize in a config file.
It means that benchmark without -boardsize option is always executed by 19x19 weight.
This pull request is a change that benchmark reads defaultBoardSize.
=> adopts defaultBoardSize for benchmark

cpp/command/gtp.cpp
Changing the MaxVisits on a running instance has a multitude of use cases. A few examples are:
- Different strength/calculation time for different stages of the game (e.g. quickly finishing in the endgame).
- AI vs AI games with different strengths per side.
The reason I made this is because I need it myself to not need multiple instances for a single game. (https://discord.com/channels/417022162348802048/583775968804732928/1026510646784839711)
I've build and tested it and it works without issues.
=> Add GTP kata-set-param maxVisits parameter

cpp/command/gtp.cpp, docs/GTP_Extensions.md, docs/GTP_Extensions_next.md
It seems that when the `printsgf` command was added, it was not added to the documentation.  This PR is designed to rectify this.  While going through the rest of the exposed sgf commands I came across one other debugging command that isn't documented.  I have also added this; however, I'm not confident that this is necessarily the sort of command that ought to be documented, so let me know if you need me to remove that, (or if I got the description of the command wrong.)
=> Added missing gtp extension commands to documentation.

cpp/command/tune.cpp, cpp/neuralnet/openclbackend.cpp, cpp/neuralnet/openclhelpers.cpp, cpp/neuralnet/openclhelpers.h, cpp/neuralnet/opencltuner.cpp, cpp/neuralnet/opencltuner.h
It seems like that on GPUs that have dynamic boost, it's possible that different parts of the tuner result in different loads on the GPU, resulting in the GPU itself choosing to run at wildly different clock speeds during different parts of tuning, which causes the tuner to measure incomparable performance between different kernels, causing the tuner to sometimes make bad choices. For example, FP16 tensor cores might be faster, but if the GPU was running at a lower clock speed during that time, then they might *appear* to be slower, and the tuner would wrongly choose not to use tensor cores.
This PR adds a background thread during tuning that just churns on the GPU doing a bunch of extra matrix multiplications to put the GPU under continual load, to encourage the GPU to stay at a …
=> Add dummy thread to add load to the GPU during opencl tuning

cpp/command/analysis.cpp
`parseInteger()` in `analysis.cpp` generates an `{error}` object (for the GUI) when it fails; it also returns false, but when the main loop sees the false return value, it also generates an error, leading to 2 `{error}` objects being sent to the GUI.
This PR removes the duplication.
Note: not actually tested. I've no C++ compiler.
=> remove duplicate error messages for bad board size

cpp/search/search.cpp, cpp/search/search.h, cpp/search/searchexplorehelpers.cpp
It is cleared anyway, so it can just as well be put on the stack.
=> Remove superfluous buffer

cpp/CMakeLists.txt
so that in cmake, we can use:
-DUSE_CACHE_TENSORRT_PLAN=1
or
-DUSE_CACHE_TENSORRT_PLAN=0
to turn on/off the trt plan cache
=> add plan cache to cmake opts

cpp/command/match.cpp, cpp/program/play.cpp
This Pull Request addresses two warnings generated during the build process of KataGo regarding the copying of objects in range-based for loops. The warnings are related to unnecessary copying of std::pair<int, int> objects in play.cpp and match.cpp.
**Warnings Addressed:**
```
/root/KataGo/cpp/program/play.cpp: In member function 'void GameInitializer::initShared(ConfigParser&, Logger&)':
/root/KataGo/cpp/program/play.cpp:366:32: warning: loop variable 'bSize' creates a copy from type 'const std::pair<int, int>' [-Wrange-loop-construct]
366 |   for(const std::pair<int,int> bSize: allowedBSizes) {
|                                ^~~~~
/root/KataGo/cpp/program/play.cpp:366:32: note: use reference type to prevent copying
366 |   for(const std::pair<int,int> bSize: allowedBSizes) {
| …
```
=> Fix Warnings for Copying in Range-based For Loops

README.md
The current command has a slightly broken pattern, and fails to find `gtp_example.cfg`.
=> README: fix grep usage in macOS instructions

python/humanslnet_gui.py
Added the following keybinds:
- Left arrow + Shift: Go 10 moves back
- Right arrow + Shift: Go 10 moves forward
- Up arrow: Go to the end of the game
- Down arrow: Go to the start of the game
When loading an sgf, the board was always rotates 90 degrees to the right.
GameState uses a coordinate pivot point at the top left while Sgfmill seems to use a different system. I fixed this by swapping x and y and inverting x when the sgf data is exported from Sgfmill into a GameState.
=> HSL GUI keybinds and board rotation fix

docs/GraphSearch.md
Minor fix, replacing `it's` with the correct form `its`. Thanks for the great docs!
=> Fix typo in GraphSearch.md

Compiling.md
Added a bit clearer instructions how to build zlib on Windows to make the build process easier
=> Improve zlib build instructions on Windows

cpp/neuralnet/metalbackend.cpp, cpp/neuralnet/metalbackend.swift
- Updated the `batchNormLayerDescToSwift` function to utilize merged scale and bias pointers.
- Modified the `SWBatchNormLayerDesc` struct to remove individual mean, variance, scale, and bias pointers, replacing them with mergedScale and mergedBias.
- Adjusted the creation and handling of scale and bias data in the `BatchNormLayer` class for the merged scale and bias.
This commit has been verified by `./rungpuerrortest.sh`.
```
: batched current cfg error vs reference winrateError:         0.00002%  0.00004%  0.00008%  0.00014%
: batched current cfg error vs reference leadError:            0.00001   0.00001   0.00002   0.00003
: batched current cfg error vs reference scoreMeanError:       0.00001   0.00001   0.00002   0.00004
: batched current cfg error vs reference scoreStdevError: …
```
=> Fix batch normalization issue in Metal backend

cpp/neuralnet/metalbackend.cpp
This pull request addresses build warnings and errors encountered in both Ninja and Xcode when compiling the Metal backend code.
Ninja Warning: Resolved a warning indicating that a non-void function may not return a value in all control paths. Added a placeholder return for the ACTIVATION_MISH_SCALE8 and default cases.
Xcode Error: Fixed an error in Xcode related to the same issue by ensuring that the default case in the activationLayerDescToSwift function also returns a value.
No behavioral changes to the existing functionality, as the placeholders are intended only for compilation purposes.
=> Fix build warnings and errors in Metal backend
